// api/index.js (AUTO-GENERATED by DevOps Panel)
// Serverless Entry - Vercel → Express Bridge
const path = require('path');

// Point to the Express app and DB connector
const appPath = path.join(__dirname, '..', 'backend', 'src', 'app.js');
const dbPath = path.join(__dirname, '..', 'backend', 'src', 'db', 'db.js');

// Vercel serverless handler
module.exports = async (req, res) => {
  try {
    // Connect to MongoDB BEFORE Express processes the request
    const connectDB = await import(dbPath);
    await connectDB.default();

    // Use dynamic import() for ES Module compatibility
    const appModule = await import(appPath);
    const app = appModule.default;

    // Handle the request
    await new Promise((resolve, reject) => {
      app(req, res, (err) => {
        if (err) reject(err);
        else resolve();
      });
    });
  } catch (error) {
    console.error('[API] Handler error:', error.message);
    res.status(500).json({ error: 'Internal Server Error', message: error.message });
  }
};
